default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  # local
  username: 'postgres'
  password: 123
  # could9
  # username: 'username'
  # password: 'password'
  # host: <%= ENV['IP'] %>

development:
  <<: *default
  database: mz_youth_development

test:
  <<: *default
  database: mz_youth_test
